// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: error_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameServerServices.ErrorCode {

  /// <summary>Holder for reflection information generated from error_code.proto</summary>
  public static partial class ErrorCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for error_code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBlcnJvcl9jb2RlLnByb3RvEgplcnJvcl9jb2RlKkcKCUVycm9yQ29kZRIL",
            "CgdTVUNDRVNTEAASFAoPSU5WQUxJRF9SRVFVRVNUEOkHEhcKElBBU1NXT1JE",
            "X0lOQ09SUkVDVBCRTkI5WhgvdGNwL2Vycm9yQ29kZTtlcnJvckNvZGWqAhxH",
            "YW1lU2VydmVyU2VydmljZXMuRXJyb3JDb2RlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameServerServices.ErrorCode.ErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// option allow_alias = true;
  /// </summary>
  public enum ErrorCode {
    [pbr::OriginalName("SUCCESS")] Success = 0,
    [pbr::OriginalName("INVALID_REQUEST")] InvalidRequest = 1001,
    [pbr::OriginalName("PASSWORD_INCORRECT")] PasswordIncorrect = 10001,
  }

  #endregion

}

#endregion Designer generated code
