// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameServerServices.MessageType {

  /// <summary>Holder for reflection information generated from message_type.proto</summary>
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for message_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJtZXNzYWdlX3R5cGUucHJvdG8SDG1lc3NhZ2VfdHlwZSpQCgtNZXNzYWdl",
            "VHlwZRILCgdVTktOT1dOEAASGgoWTVNHX0hFTExPV09STERfUkVRVUVTVBAB",
            "EhgKFE1TR19IRUxMT1dPUkxEX1JFUExZEAJCO1oYL21lc3NhZ2VUeXBlO21l",
            "c3NhZ2VUeXBlqgIeR2FtZVNlcnZlclNlcnZpY2VzLk1lc3NhZ2VUeXBlYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameServerServices.MessageType.MessageType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MessageType {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("MSG_HELLOWORLD_REQUEST")] MsgHelloworldRequest = 1,
    [pbr::OriginalName("MSG_HELLOWORLD_REPLY")] MsgHelloworldReply = 2,
  }

  #endregion

}

#endregion Designer generated code
