// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameServerServices.MessageType {

  /// <summary>Holder for reflection information generated from message_type.proto</summary>
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for message_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJtZXNzYWdlX3R5cGUucHJvdG8SDG1lc3NhZ2VfdHlwZSqGAQoLTWVzc2Fn",
            "ZVR5cGUSCwoHVU5LTk9XThAAEhoKFk1TR19IRUxMT1dPUkxEX1JFUVVFU1QQ",
            "ARIYChRNU0dfSEVMTE9XT1JMRF9SRVBMWRACEhkKFU1TR19VU0VSX1JFR0lT",
            "VEVSX1JFURADEhkKFU1TR19VU0VSX1JFR0lTVEVSX1JFUxAEQj9aHC90Y3Av",
            "bWVzc2FnZVR5cGU7bWVzc2FnZVR5cGWqAh5HYW1lU2VydmVyU2VydmljZXMu",
            "TWVzc2FnZVR5cGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameServerServices.MessageType.MessageType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MessageType {
    /// <summary>
    /// option allow_alias = true;
    /// Only values in range [0, 65535] are allowed for TCP use
    /// </summary>
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("MSG_HELLOWORLD_REQUEST")] MsgHelloworldRequest = 1,
    [pbr::OriginalName("MSG_HELLOWORLD_REPLY")] MsgHelloworldReply = 2,
    [pbr::OriginalName("MSG_USER_REGISTER_REQ")] MsgUserRegisterReq = 3,
    [pbr::OriginalName("MSG_USER_REGISTER_RES")] MsgUserRegisterRes = 4,
  }

  #endregion

}

#endregion Designer generated code
